[package]
name = "bevy_window_utils_test"
version = "0.15.4"
edition = "2024"
publish = false
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.16.0-rc.5"
bevy_window_utils = { path = "../bevy_window_utils" }
